# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EGProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EGProject

	pod 'Masonry', '~> 1.0.0'
	pod 'MBProgressHUD', '~> 0.9.1'
	pod 'MJRefresh', '~> 3.1.7'

target 'EGProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EGProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
